//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cостав_Заказа
    {
        public int id { get; set; }
        public int id_заказа { get; set; }
        public int id_товара { get; set; }
        public string код_товара { get; set; }
        public int количество_товара { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
