//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Cостав_Заказа = new HashSet<Cостав_Заказа>();
        }
    
        public int id_заказа { get; set; }
        public Nullable<System.DateTime> дата_заказа { get; set; }
        public Nullable<System.DateTime> дата_доставки { get; set; }
        public Nullable<int> пункт_выдачи { get; set; }
        public Nullable<int> id_пользователя { get; set; }
        public string код_для_получения { get; set; }
        public string статус_заказа { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cостав_Заказа> Cостав_Заказа { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Пункты_выдачи Пункты_выдачи { get; set; }
    }
}
