//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.Cостав_Заказа = new HashSet<Cостав_Заказа>();
        }
    
        public int id { get; set; }
        public string Артикул { get; set; }
        public string наименование { get; set; }
        public string единица_измерения { get; set; }
        public decimal стоимость { get; set; }
        public string размер_максимально_возможной_скидки { get; set; }
        public string производитель { get; set; }
        public string поставщик { get; set; }
        public int категория_товара { get; set; }
        public string действующая_скидка { get; set; }
        public string количество_на_складе { get; set; }
        public string описание { get; set; }
        public string изображение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cостав_Заказа> Cостав_Заказа { get; set; }
        public virtual Категория_Товаров Категория_Товаров { get; set; }
    }
}
